const ENEMIES = {
  grunt: {
    name: "Raider",
    sprite: "grunt",
    walk: true,
    hp: 28,
    dmg: 5,
    armor: 0,
    speed: 70,
    atkRate: 0.85,
    reach: 78,
    keep: 78,
    gold: 8,
    magic: 2,
    color: "#7a8a4a",
  },
  shield: {
    name: "Shield",
    sprite: "shield",
    hp: 46,
    dmg: 4,
    armor: 7,
    speed: 48,
    atkRate: 0.7,
    reach: 86,
    keep: 86,
    gold: 12,
    magic: 2,
    color: "#8a6a3a",
  },
  berserk: {
    name: "Berserker",
    sprite: "berserk",
    hp: 26,
    dmg: 11,
    armor: 0,
    speed: 95,
    atkRate: 1.15,
    reach: 80,
    keep: 80,
    gold: 14,
    magic: 3,
    color: "#a33a2a",
    enrage: true,
  },
  archer: {
    name: "Archer",
    sprite: "archer",
    hp: 20,
    dmg: 7,
    armor: 0,
    speed: 62,
    atkRate: 0.7,
    reach: 78,
    keep: 310,
    gold: 13,
    magic: 4,
    color: "#4a6a3a",
    projectile: "arrow",
    projSpeed: 420,
    atkRange: 420,
  },
  mage: {
    name: "Mage",
    sprite: "mage",
    hp: 18,
    dmg: 14,
    armor: 0,
    speed: 50,
    atkRate: 0.42,
    reach: 78,
    keep: 360,
    gold: 16,
    magic: 8,
    color: "#3a4aaa",
    projectile: "bolt",
    projSpeed: 280,
    atkRange: 460,
  },
  healer: {
    name: "Healer",
    sprite: "healer",
    hp: 22,
    dmg: 3,
    armor: 0,
    speed: 52,
    atkRate: 0.55,
    reach: 78,
    keep: 340,
    gold: 15,
    magic: 7,
    color: "#c9a227",
    heal: 10,
    healRate: 2.4,
    atkRange: 400,
  },
  assassin: {
    name: "Assassin",
    sprite: "assassin",
    hp: 22,
    dmg: 4,
    armor: 0,
    speed: 88,
    atkRate: 1.05,
    reach: 70,
    keep: 70,
    gold: 14,
    magic: 4,
    color: "#3a3a48",
    crit: 0.4,
    shadowstep: true,
  },
  butcher: {
    name: "The Butcher",
    sprite: "butcher",
    boss: true,
    scale: 1.55,
    hp: 90,
    dmg: 14,
    armor: 2,
    speed: 38,
    atkRate: 0.55,
    reach: 110,
    keep: 110,
    gold: 48,
    magic: 16,
    color: "#c44a2a",
    enrage: true,
  },
  ironhide: {
    name: "Ironhide",
    sprite: "ironhide",
    boss: true,
    scale: 1.5,
    hp: 110,
    dmg: 11,
    armor: 8,
    speed: 28,
    atkRate: 0.48,
    reach: 115,
    keep: 115,
    gold: 58,
    magic: 14,
    color: "#6a7080",
  },
  skycleaver: {
    name: "Skycleaver",
    sprite: "skycleaver",
    boss: true,
    scale: 1.5,
    hp: 75,
    dmg: 12,
    armor: 1,
    speed: 44,
    atkRate: 0.55,
    reach: 90,
    keep: 280,
    gold: 62,
    magic: 18,
    color: "#8a6a3a",
    projectile: "arrow",
    projSpeed: 460,
    volley: 3,
    atkRange: 480,
  },
  stormcaller: {
    name: "Stormcaller",
    sprite: "stormcaller",
    boss: true,
    scale: 1.48,
    hp: 70,
    dmg: 15,
    armor: 0,
    speed: 36,
    atkRate: 0.38,
    reach: 90,
    keep: 330,
    gold: 70,
    magic: 24,
    color: "#5a4ad0",
    projectile: "bolt",
    projSpeed: 300,
    volley: 2,
    atkRange: 500,
  },
  sunfallen: {
    name: "The Sunfallen",
    sprite: "sunfallen",
    boss: true,
    scale: 1.48,
    hp: 95,
    dmg: 10,
    armor: 3,
    speed: 34,
    atkRate: 0.5,
    reach: 95,
    keep: 240,
    gold: 80,
    magic: 22,
    color: "#d07030",
    heal: 14,
    healRate: 2.1,
    projectile: "bolt",
    projSpeed: 260,
    atkRange: 420,
  },
};

const BOSS_ORDER = ["butcher", "ironhide", "skycleaver", "stormcaller", "sunfallen"];

// The campaign is tuned as five ten-wave chapters; endless adds a steeper curve.
const RUN_UPGRADES = [
  { id: "iron", name: "Steel", desc: "+1.5 damage", icon: "⚔", max: 40,
    cost: lv => Math.floor(16 * 1.16 ** lv), apply: h => { h.dmg += 1.5; } },
  { id: "vital", name: "Resolve", desc: "+12 HP, heal 12, +0.6 armor", icon: "♥", max: 40,
    cost: lv => Math.floor(18 * 1.16 ** lv),
    apply: h => { h.maxHp += 12; h.hp = Math.min(h.maxHp, h.hp + 12); h.armor += 0.6; } },
  { id: "swift", name: "Tempo", desc: "+0.04 attacks/sec", icon: "»", max: 30,
    cost: lv => Math.floor(20 * 1.18 ** lv), apply: h => { h.atkRate = Math.min(2.5, h.atkRate + 0.04); } },
];

const BRANCHES = [
  { id: "vanguard", name: "Vanguard", desc: "Hold the line. Return home to shield yourself." },
  { id: "ravager", name: "Ravager", desc: "Break crowds. Whirlwind leaves enemies bleeding." },
  { id: "spellblade", name: "Spellblade", desc: "Time your magic. Mend empowers your next strike." },
];
const PRESTIGE_UPGRADES = BRANCHES.flatMap(b => [
  { id: b.id + "_body", branch: b.id, name: "Conditioning", desc: "+5% starting HP per rank", max: 3, cost: lv => 5 + lv * 5 },
  { id: b.id + "_craft", branch: b.id, name: "Discipline",
    desc: b.id === "vanguard" ? "+1 armor per rank" : b.id === "ravager" ? "+4% damage per rank" : "+0.2 mana/sec per rank",
    max: 3, cost: lv => 5 + lv * 5 },
  { id: b.id + "_keystone", branch: b.id, name: b.id === "vanguard" ? "Safe Return" : b.id === "ravager" ? "Open Wounds" : "Spellsteel",
    desc: b.id === "vanguard" ? "Return: 15% HP shield for 4s (10s cooldown)" : b.id === "ravager" ? "Whirlwind: bleed for 45% damage over 3s" : "Mend: next weapon strike deals +60% damage",
    max: 1, requires: 6, cost: () => 25 },
]);
const TALENTS = [
  { id: "reach", name: "Sweeping Steel", desc: "+25 Whirlwind reach and +8% Whirlwind damage per rank" },
  { id: "duelist", name: "Duelist", desc: "+12% weapon damage against isolated enemies per rank" },
  { id: "edge", name: "Keen Edge", desc: "+5% critical chance per rank (35% total cap)" },
  { id: "leech", name: "Blood Drinker", desc: "+2% lifesteal per rank (8% total cap; area hits heal at 25%)" },
  { id: "ward", name: "Second Wind", desc: "Mend heals an extra 3% max HP per rank" },
  { id: "fortune", name: "Scavenger", desc: "+8% kill gold per rank" },
];
const CHAPTERS = ["The Treeline", "Broken Shields", "The Hunting Ground", "Storm Road", "The Last Light"];

function waveCount(n) { return Math.min(7, Math.max(1, Math.ceil(n / 2))); }
function isBossWave(n) { return n > 0 && n % 10 === 0; }
function bossTypeFor(n) { return BOSS_ORDER[(Math.floor(n / 10) - 1) % BOSS_ORDER.length]; }
function waveRoster(n) {
  if (isBossWave(n)) return [bossTypeFor(n)];
  const packs = [
    ["grunt", "grunt", "shield", "berserk", "archer"],
    ["shield", "berserk", "grunt", "archer", "healer", "grunt", "mage"],
    ["assassin", "archer", "grunt", "berserk", "mage", "shield", "healer"],
    ["mage", "shield", "berserk", "healer", "archer", "assassin", "grunt"],
    ["shield", "mage", "assassin", "healer", "berserk", "archer", "shield"],
  ];
  const chapter = Math.min(4, Math.floor((n - 1) / 10));
  if (n <= 2) return Array(waveCount(n)).fill("grunt");
  const pack = packs[chapter];
  return Array.from({ length: waveCount(n) }, (_, i) => pack[(i + (chapter ? n % pack.length : 0)) % pack.length]);
}
function waveScale(n) {
  const extra = Math.max(0, n - 50);
  return { hp: 1.065 ** (n - 1) * 1.035 ** extra,
    dmg: 1.03 ** (n - 1) * 1.025 ** extra, gold: 1 + (n - 1) * 0.14 };
}
function nextWaveDelay() { return 18; }
