// Run with NODE_PATH pointing at a local Playwright installation and the game served locally.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
(async () => {
 const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || '/usr/bin/chromium', headless: true, args: ['--no-sandbox'] });
 try {
 const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
 const errors = []; page.on('pageerror', e => errors.push(e.message));
 await page.route('https://fonts.googleapis.com/**', r => r.abort());
 // Deterministically step the real combat code without animation or audio clocks.
 await page.route('**/js/game.js', async r => {
  let s = fs.readFileSync(path.join(__dirname, '../js/game.js'), 'utf8');
  s = s.replace('  function sfx(freq, dur, type, vol) {', '  function sfx(freq, dur, type, vol) { return;');
  s = s.replace('  resize();\n  loadAll()', `  window.test = { update, spawnWave, hitEnemy, hitHero, swing, whirlwind, whirlHit, mend, charge, buyRun, saveRun, showTalent, chooseTalent, showVictory, bankGlory, gloryFor, togglePause, callWave, respec, resumeRun, resize, render, rank, keystone, get state() { return state; }, get loaded() { return meta.loaded; } };\n  resize();\n  loadAll()`);
  s = s.replace('.then(() => requestAnimationFrame(loop))', '.then(() => render())');
  await r.fulfill({ contentType: 'text/javascript', body: s });
 });
 await page.goto(process.env.GAME_URL || 'http://127.0.0.1:8766');
 await page.waitForFunction(() => window.test?.loaded);
 await page.click('#btn-start');
 assert.equal(await page.locator('#upgrades .row').count(), 3);
 const results = await page.evaluate(() => {
   const assert = (ok, msg) => { if (!ok) throw Error(msg); };
   const t = window.test, u = window.unending, r = u.run;
   t.update(.5); assert(r.wave === 1, 'first wave');
   const initialX = r.enemies[0].x;
   t.togglePause(); const hp = r.hero.hp, time = r.elapsed, gold = r.gold;
   t.mend(); t.whirlwind(); t.buyRun('iron'); t.update(1);
   assert(r.hero.hp === hp && r.elapsed === time && r.gold === gold && !r.hero.whirl, 'pause blocks actions');
   t.togglePause();
   r.hero.hp = 50; r.hero.leech = .08; r.enemies[0].hp = 1;
   t.hitEnemy(r.enemies[0], 10000, false, true);
   assert(Math.abs(r.hero.hp - 50.02) < .001, 'leech respects overkill and area penalty');
   assert(r.cleared.includes(1) && r.waveTimer <= 2.5, 'clear accelerates next wave');
   const earned = t.gloryFor(); t.bankGlory(); const bank = u.persist.glory; t.bankGlory();
   assert(u.persist.glory === bank && earned === 1, 'bank is idempotent');
   r.claimedGlory = 0; t.bankGlory(); assert(u.persist.glory === bank, 'old snapshot cannot repay banked Glory');
   r.wave = 4; r.enemies = []; r.ledger = {}; t.callWave(); t.update(.05); u.smite(); t.update(.05);
   assert(t.state === 'talent' && r.offers.length === 3, 'wave 5 talent');
   const offers = [...r.offers]; t.saveRun();
   t.chooseTalent(offers[0]); assert(Object.keys(r.talents).length === 1, 'talent choice');
   r.gold = 1e9; t.buyRun('iron', 'max'); assert(r.levels.iron === 40, 'rank cap');
   const balance = r.gold; t.buyRun('iron', 'max'); assert(r.gold === balance, 'max rank cannot spend');
   r.enemies = []; r.ledger = {}; r.wave = 9; t.callWave(); t.update(.05);
   assert(r.enemies[0].def.boss, 'boss spawns');
   t.update(50); assert(r.wave === 10, 'boss blocks waves');
   u.smite(); t.update(.05); if (t.state === 'talent') t.chooseTalent(r.offers[0]);
   assert(r.bosses.includes(10) && u.persist.milestones.includes(10), 'boss reward');
   t.saveRun();
   return { initialX, earned, offers, glory: u.persist.glory };
 });
 await page.reload(); await page.waitForFunction(() => window.test?.loaded);
 await page.click('#btn-resume');
 assert.equal(await page.evaluate(() => unending.run.wave), 10);
 assert.equal(await page.evaluate(() => unending.run.levels.iron), 40);
 await page.evaluate(() => { const r=unending.run; r.enemies=[]; r.ledger={}; r.wave=49; test.callWave(); test.update(.05); unending.smite(); test.update(.05); if(test.state==='talent') test.chooseTalent(r.offers[0]); });
 assert.equal(await page.evaluate(() => test.state), 'victory');
 await page.screenshot({path:'/tmp/unending-victory.png'});
 const victoryGlory = await page.evaluate(() => unending.persist.glory);
 await page.reload(); await page.waitForFunction(() => window.test?.loaded); await page.click('#btn-resume');
 assert.equal(await page.evaluate(() => unending.persist.glory), victoryGlory);
 await page.click('#btn-endless');
 await page.evaluate(() => { test.callWave(); test.update(.05); });
 assert.equal(await page.evaluate(() => unending.run.wave), 51);
 await page.evaluate(() => unending.kill());
 assert.equal(await page.evaluate(() => localStorage.getItem('unending-run-v2')), null);
 await page.screenshot({path:'/tmp/unending-prestige.png'});
 await page.evaluate(() => { unending.persist.glory=1000; test.respec(); });
 for (let i=0;i<3;i++) await page.locator('.branch').first().locator('.row button').nth(0).click();
 for (let i=0;i<3;i++) await page.locator('.branch').first().locator('.row button').nth(1).click();
 await page.locator('.branch').first().locator('.row button').nth(2).click();
 assert.equal(await page.evaluate(() => test.keystone('vanguard')), true);
 await page.click('#btn-respec');
 assert.equal(await page.evaluate(() => unending.persist.glory), 1000);
 await page.evaluate(() => {
  const assert=(ok,msg)=>{if(!ok)throw Error(msg)};
  const t=test,u=unending;
  u.persist.branch='vanguard';u.persist.prest={vanguard_body:3,vanguard_craft:3,vanguard_keystone:1};u.startRun();
  t.charge();t.update(.6);t.charge();t.update(.6);
  assert(u.run.hero.shield>0,'Vanguard shield on return');
  const hp=u.run.hero.hp;t.hitHero(10,200,false,'Test');assert(u.run.hero.hp===hp,'shield absorbs damage');
  u.persist.branch='ravager';u.persist.prest={ravager_keystone:1};u.startRun();t.update(.5);
  let e=u.run.enemies[0];e.x=u.run.hero.x+72;e.hp=e.maxHp=1000;
  t.whirlHit();assert(e.bleedT===3,'Ravager applies bleed');
  u.run.hero.hp=50;u.run.hero.leech=.08;t.hitEnemy(e,10,false,true,true);assert(u.run.hero.hp===50,'bleed does not leech');
  u.persist.branch='spellblade';u.persist.prest={spellblade_keystone:1};u.startRun();t.update(.5);
  u.run.hero.hp=50;t.mend();assert(u.run.hero.empowered,'Mend empowers Spellblade');
  t.swing(1);assert(u.run.hero.empowered,'missing preserves empowerment');
  e=u.run.enemies[0];e.x=u.run.hero.x+72;e.hp=e.maxHp=1000;u.run.hero.crit=0;
  t.swing(1);assert(!u.run.hero.empowered&&Math.abs(e.hp-(1000-u.run.hero.dmg*1.6))<.001,'strike consumes empowerment');
  u.run.autoBuy='balanced';u.run.gold=100;t.update(.5);assert(u.run.purchases>0,'balanced spending buys ranks');
  u.run.pendingChoices=1;t.showTalent();t.saveRun();window.savedOffers=[...u.run.offers];
 });
 const savedOffers=await page.evaluate(()=>window.savedOffers);
 await page.reload();await page.waitForFunction(()=>window.test?.loaded);await page.click('#btn-resume');
 assert.equal(await page.evaluate(()=>test.state),'talent');
 assert.deepEqual(await page.evaluate(()=>unending.run.offers),savedOffers);
 await page.locator('.talent-card').first().click();
 await page.evaluate(()=>{unending.kill();});
 await page.click('#btn-again'); await page.evaluate(() => { test.update(.5); test.render(); });
 await page.screenshot({path:'/tmp/unending-fight.png'});
 await page.setViewportSize({width:1920,height:1080});
 await page.evaluate(() => { unending.startRun(); test.update(.5); });
 assert.equal(await page.evaluate(() => unending.run.enemies[0].x), results.initialX);
 await page.evaluate(() => { localStorage.clear(); localStorage.setItem('unending-save-v1',JSON.stringify({glory:7,bestWave:20,prest:{blood:2,might:3,purse:1,greed:2,fate:2,spark:1}})); });
 await page.reload(); await page.waitForFunction(() => window.test?.loaded);
 assert.equal(await page.evaluate(() => unending.persist.glory), 36);
 assert.equal(await page.evaluate(() => unending.persist.bestWave), 19);
 assert.ok(await page.evaluate(() => localStorage.getItem('unending-save-v1')));
 assert.deepEqual(errors, []);
 console.log('PASS: combat, pause, leech, wave clears, talent choices, purchase caps, bosses, Glory banking, save/resume, campaign/endless, prestige/refund, viewport pacing, legacy migration.');
 console.log(JSON.stringify(results));
 } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode=1; });
